apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: welcome-cert
  namespace: default
spec:
  secretName: welcome-cert-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - welcome.local
